branches:
  only:
  - master
language: node_js
node_js:
- 9.10.0
before_install:
- sudo apt-get update
- sudo apt-get install -y python3 python3-pip
- pip3 install awscli --upgrade --user
install:
- npm install
script:
- npm run-script build
- npm run-script deploy
env:
  global:
  - secure: lqFjt530fEuBazKnk0aszSrEM8xaiZp/+yjzIDUQtkL9iS6CQKw0WjkB4wNeVUVTCV5ghJz7FK8YQQszDt6NGmS4FYOA6NpHAYqxDntdgtS3tRDcbrTflSBZSi0PQI7+xFrLiurU3SdplvUz53voGVQq/tvxMzEACqtb+q4D61/PeDcbhlTW5s9s7Q+HDwzo9VvpbP06DumK8mt+GYu+rps1ZELM0o7EovY5XDSX58FKSWD3yZvsuuAuSjrB5DJIOpvQq3aazilWfAMBG8z/zbB6JZKEFWYPf5LsYDlfyW/L+1NwYJYDwlrq06k0nBjLBVbtUwV+/VzCfT7308Qb2WV5ZSHYyPpDGp2vSl/lMWHJ5au6AykTTjEfFhTGVNFg0nDLwrTEwbHrplh1+niRX8ot4Y81qXRkhAdbdJE1uN0M6ZyJpGKTXQ+pQ+DRLcBfa9k9EEeOx4X1k5TiWhiYv+9Du/M22EQgaTI88BPAQItSOb3vOXk7qquJcHZJkjWBQkNTSNrmdgHjCAKdzyWIqQfMmXPgGbmKZQEOmiUEZa38FC1f9RNOs18nNsiZe3tCZxWVnGQecUduOdUwlyV61MADBDgF88yOi24EuUnPHK1tapv2Z6vo6642JOCpZPlE+cTIKVrUAA2Me1yKmsQX29+wh8qUjQCGcYdjRufyErw=
  - secure: lbBOTlxbQLXn0/nZvE0FDRUkZoxA2ef4tdDB2HY+uj88MszfzzD7dWzZjZOZos63V9uPfEuaK0Nz/zbhsXVmZBUl4dQaWB6KVTuzaVrTMuvHbPd284SMCWuYpLKR7HsDlrN1iD+/iigk4Xnryj0RU85HEbZ6DK7kbvx21Kw9aen0Q+ne7PL3SWPODge3lWc2txpnWBCkIvSoUWgtDvRZGDyAIHJSq/E4DcLLYzwmcJ3iJlicoYFrsHaIGnqFKrTORZgAXLZGzGIX9GUBwbCNZCHKbRhtnCtN1CSDQfr86HDUz4hzAsLwE8RhQg4lx/TGgEcgNzJDmVv4WYh4h58etcKbIvpPlaUUtzXGQ2n/WImyY6GfqKagtsRHkObm0kfn3fDVPEnmOcDHYVJrPY9rzkyzgWpGonC/sQ0Ktuc6Fssc6wSZgyl8pmu1C+Z5wcn46GKq3J8U2ZsLnvLr/1tfwzim0WktRcR4NHLmVlhAx1Xh3MIlLT1yPFBEKfpprmukLHnkeNJ8IX1EfesI9d7lRKQcPk0wheIbU6Zn6ByRit3Ix5vZ6GjQDj+YKt9071+qNtKudkbiP1+1234KSlG36a2L8AerNSKuZ/4jRKM3nuPl+Tg3PyHiB3Zd3jT8sexi+e4ov7QUjP+LYzNbM/Uy3n6IYiRNVpJCtq54hAPpPPE=
